# Generated by Django 6.0.3 on 2026-04-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('completada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
    ]
